apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: todo-db
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: todo_db
      owner: todo_user
      secret:
        name: db-secret
