apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
      Flush         5
      Log_Level     info

    [INPUT]
      Name          tail
      Path          /var/log/containers/*.log
      Parser        docker
      Tag           kube.*

    [FILTER]
      Name          kubernetes
      Match         kube.*
      Merge_Log     On

    [OUTPUT]
      Name          http
      Match         kube.*
      Host          logstash
      Port          5044
      Format        json_lines
